/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_ISP_ALGO_PARAM_V2_ISP_ALGO_PARAM_PB_H_INCLUDED
#define PB_ISP_ALGO_PARAM_V2_ISP_ALGO_PARAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _isp_algo_param_header_value_t { 
    ISP_ALGO_PARAM_HEADER_ZERO = 0, 
    ISP_ALGO_PARAM_HEADER_MAGIC = 1095518031, 
    ISP_ALGO_PARAM_HEADER_V1_0 = 65536, 
    ISP_ALGO_PARAM_HEADER_V1_1 = 65537, 
    ISP_ALGO_PARAM_HEADER_V1_2 = 65538, 
    ISP_ALGO_PARAM_HEADER_V1_3 = 65539, 
    ISP_ALGO_PARAM_HEADER_V1_4 = 65540, 
    ISP_ALGO_PARAM_HEADER_VERSION = 65540 
} isp_algo_param_header_value_t;

typedef enum _isp_algo_param_ae_v1_high_light_mode { 
    ISP_PARAM_AE_V1_NON_HIGH_LIGHT = 0, 
    ISP_PARAM_AE_V1_ENTER_HIGH_LIGHT = 1, 
    ISP_PARAM_AE_V1_EXIT_HIGH_LIGHT = 2 
} isp_algo_param_ae_v1_high_light_mode;

typedef enum _isp_algo_param_awb_v1_mixct_mode { 
    ISP_PARAM_AWB_V1_MIXCT_NONE = 0, 
    ISP_PARAM_AWB_V1_MIXCT_H_CT_MODE = 1, 
    ISP_PARAM_AWB_V1_MIXCT_L_CT_MODE = 2 
} isp_algo_param_awb_v1_mixct_mode;

/* Struct definitions */
typedef struct _isp_algo_param_header_t { 
    isp_algo_param_header_value_t magic; 
    isp_algo_param_header_value_t version; 
} isp_algo_param_header_t;

typedef struct _isp_algo_param_index_t { 
    uint8_t indexes[2]; 
    uint8_t indexes0[2]; 
    uint8_t indexes1[2]; 
} isp_algo_param_index_t;

typedef struct _isp_algo_param_point_t { 
    uint16_t x; 
    uint16_t y; 
} isp_algo_param_point_t;

typedef struct _isp_algo_param_common_t { 
    char name[32]; 
    isp_algo_param_index_t index; 
} isp_algo_param_common_t;

typedef struct _isp_algo_param_ae_v1_t { 
    isp_algo_param_common_t common; 
    uint16_t y_mean; 
    float gain[4]; 
    float exposure[4]; 
    float saturated_ratio; 
    bool ae_ctrl_force; 
    uint8_t dark_sort_index; 
    uint8_t bright_sort_index; 
    uint8_t max_et_index; 
    float etgain_ratio[3]; 
    uint32_t hdr_mean[4]; 
    float hdr_over_ratio[4]; 
    uint32_t hdr_stable_info[4]; 
    float analog_gain[4]; 
    float digital_gain[4]; 
    float isp_hdr_gain[4]; 
    float isp_gain; 
    uint8_t ratio_range_index; 
    uint16_t roi_y_mean; 
    uint16_t non_roi_y_mean; 
    uint16_t frame_y_mean; 
    uint16_t same_block_num; 
    int32_t target_delta; 
    isp_algo_param_ae_v1_high_light_mode high_light_mode; 
} isp_algo_param_ae_v1_t;

typedef struct _isp_algo_param_af_v1_t { 
    isp_algo_param_common_t common; 
    bool af_ctrl_force; 
} isp_algo_param_af_v1_t;

typedef struct _isp_algo_param_awb_v1_t { 
    isp_algo_param_common_t common; 
    isp_algo_param_point_t gray_gain; 
    isp_algo_param_point_t green_gain; 
    isp_algo_param_point_t rough_gain; 
    isp_algo_param_point_t result_gain; 
    uint32_t color_temperature; 
    bool awb_ctrl_force; 
    isp_algo_param_point_t final_gain; 
    isp_algo_param_point_t gain_adj; 
    uint32_t gray_num; 
    uint32_t green_num; 
    isp_algo_param_awb_v1_mixct_mode mixct_mode; 
} isp_algo_param_awb_v1_t;

typedef struct _isp_algo_param_blc_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_blc_v1_t;

typedef struct _isp_algo_param_ccm_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_ccm_v1_t;

typedef struct _isp_algo_param_daynight_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_daynight_v1_t;

typedef struct _isp_algo_param_flick_v1_t { 
    isp_algo_param_common_t common; 
    uint16_t insert_dummy_line; 
    uint32_t cur_freq; 
    bool flick_ctrl_force; 
} isp_algo_param_flick_v1_t;

typedef struct _isp_algo_param_gamma_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_gamma_v1_t;

typedef struct _isp_algo_param_high_temp_v1_t { 
    isp_algo_param_common_t common; 
    bool high_temp_en; 
    uint32_t sensor_temperature; 
} isp_algo_param_high_temp_v1_t;

typedef struct _isp_algo_param_mlsc_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_mlsc_v1_t;

typedef struct _isp_algo_param_nlsc_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_nlsc_v1_t;

typedef struct _isp_algo_param_spe_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_spe_v1_t;

typedef struct _isp_algo_param_texture_v1_t { 
    isp_algo_param_common_t common; 
    pb_size_t nests_count;
    isp_algo_param_common_t nests[16]; 
} isp_algo_param_texture_v1_t;

typedef struct _isp_algo_param_uvtune_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_uvtune_v1_t;

typedef struct _isp_algo_param_wdr_v1_t { 
    isp_algo_param_common_t common; 
    uint32_t day_night; 
    uint16_t low_bound; 
    uint8_t wdr_level; 
    bool wdr_ctrl_force; 
    uint16_t hist_contrast_origin; 
    uint16_t hist_contrast; 
} isp_algo_param_wdr_v1_t;

typedef struct _isp_algo_param_ygamma_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_ygamma_v1_t;

typedef struct _isp_algo_param_ygc_v1_t { 
    isp_algo_param_common_t common; 
} isp_algo_param_ygc_v1_t;

typedef struct _isp_algo_param_ae_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_ae_v1_t v1;
    } entry; 
} isp_algo_param_ae_t;

typedef struct _isp_algo_param_af_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_af_v1_t v1;
    } entry; 
} isp_algo_param_af_t;

typedef struct _isp_algo_param_awb_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_awb_v1_t v1;
    } entry; 
} isp_algo_param_awb_t;

typedef struct _isp_algo_param_blc_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_blc_v1_t v1;
    } entry; 
} isp_algo_param_blc_t;

typedef struct _isp_algo_param_ccm_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_ccm_v1_t v1;
    } entry; 
} isp_algo_param_ccm_t;

typedef struct _isp_algo_param_daynight_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_daynight_v1_t v1;
    } entry; 
} isp_algo_param_daynight_t;

typedef struct _isp_algo_param_flick_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_flick_v1_t v1;
    } entry; 
} isp_algo_param_flick_t;

typedef struct _isp_algo_param_gamma_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_gamma_v1_t v1;
    } entry; 
} isp_algo_param_gamma_t;

typedef struct _isp_algo_param_high_temp_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_high_temp_v1_t v1;
    } entry; 
} isp_algo_param_high_temp_t;

typedef struct _isp_algo_param_mlsc_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_mlsc_v1_t v1;
    } entry; 
} isp_algo_param_mlsc_t;

typedef struct _isp_algo_param_nlsc_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_nlsc_v1_t v1;
    } entry; 
} isp_algo_param_nlsc_t;

typedef struct _isp_algo_param_spe_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_spe_v1_t v1;
    } entry; 
} isp_algo_param_spe_t;

typedef struct _isp_algo_param_texture_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_texture_v1_t v1;
    } entry; 
} isp_algo_param_texture_t;

typedef struct _isp_algo_param_uvtune_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_uvtune_v1_t v1;
    } entry; 
} isp_algo_param_uvtune_t;

typedef struct _isp_algo_param_wdr_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_wdr_v1_t v1;
    } entry; 
} isp_algo_param_wdr_t;

typedef struct _isp_algo_param_ygamma_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_ygamma_v1_t v1;
    } entry; 
} isp_algo_param_ygamma_t;

typedef struct _isp_algo_param_ygc_t { 
    pb_size_t which_entry;
    union {
        isp_algo_param_ygc_v1_t v1;
    } entry; 
} isp_algo_param_ygc_t;

typedef struct _isp_algo_param_t { 
    isp_algo_param_header_t header; 
    isp_algo_param_blc_t blc; 
    isp_algo_param_nlsc_t nlsc; 
    isp_algo_param_mlsc_t mlsc; 
    isp_algo_param_ccm_t ccm; 
    isp_algo_param_gamma_t gamma; 
    isp_algo_param_ygc_t ygc; 
    isp_algo_param_uvtune_t uvtune; 
    isp_algo_param_spe_t spe; 
    isp_algo_param_ygamma_t ygamma; 
    isp_algo_param_texture_t texture; 
    isp_algo_param_ae_t ae; 
    isp_algo_param_awb_t awb; 
    isp_algo_param_af_t af; 
    isp_algo_param_flick_t flick; 
    isp_algo_param_wdr_t wdr; 
    isp_algo_param_daynight_t daynight; 
    isp_algo_param_high_temp_t high_temp; 
} isp_algo_param_t;


/* Helper constants for enums */
#define _isp_algo_param_header_value_t_MIN ISP_ALGO_PARAM_HEADER_ZERO
#define _isp_algo_param_header_value_t_MAX ISP_ALGO_PARAM_HEADER_MAGIC
#define _isp_algo_param_header_value_t_ARRAYSIZE ((isp_algo_param_header_value_t)(ISP_ALGO_PARAM_HEADER_MAGIC+1))
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_ZERO ISP_ALGO_PARAM_HEADER_ZERO
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_MAGIC ISP_ALGO_PARAM_HEADER_MAGIC
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_V1_0 ISP_ALGO_PARAM_HEADER_V1_0
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_V1_1 ISP_ALGO_PARAM_HEADER_V1_1
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_V1_2 ISP_ALGO_PARAM_HEADER_V1_2
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_V1_3 ISP_ALGO_PARAM_HEADER_V1_3
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_V1_4 ISP_ALGO_PARAM_HEADER_V1_4
#define isp_algo_param_header_value_t_ISP_ALGO_PARAM_HEADER_VERSION ISP_ALGO_PARAM_HEADER_VERSION

#define _isp_algo_param_ae_v1_high_light_mode_MIN ISP_PARAM_AE_V1_NON_HIGH_LIGHT
#define _isp_algo_param_ae_v1_high_light_mode_MAX ISP_PARAM_AE_V1_EXIT_HIGH_LIGHT
#define _isp_algo_param_ae_v1_high_light_mode_ARRAYSIZE ((isp_algo_param_ae_v1_high_light_mode)(ISP_PARAM_AE_V1_EXIT_HIGH_LIGHT+1))
#define isp_algo_param_ae_v1_high_light_mode_ISP_PARAM_AE_V1_NON_HIGH_LIGHT ISP_PARAM_AE_V1_NON_HIGH_LIGHT
#define isp_algo_param_ae_v1_high_light_mode_ISP_PARAM_AE_V1_ENTER_HIGH_LIGHT ISP_PARAM_AE_V1_ENTER_HIGH_LIGHT
#define isp_algo_param_ae_v1_high_light_mode_ISP_PARAM_AE_V1_EXIT_HIGH_LIGHT ISP_PARAM_AE_V1_EXIT_HIGH_LIGHT

#define _isp_algo_param_awb_v1_mixct_mode_MIN ISP_PARAM_AWB_V1_MIXCT_NONE
#define _isp_algo_param_awb_v1_mixct_mode_MAX ISP_PARAM_AWB_V1_MIXCT_L_CT_MODE
#define _isp_algo_param_awb_v1_mixct_mode_ARRAYSIZE ((isp_algo_param_awb_v1_mixct_mode)(ISP_PARAM_AWB_V1_MIXCT_L_CT_MODE+1))
#define isp_algo_param_awb_v1_mixct_mode_ISP_PARAM_AWB_V1_MIXCT_NONE ISP_PARAM_AWB_V1_MIXCT_NONE
#define isp_algo_param_awb_v1_mixct_mode_ISP_PARAM_AWB_V1_MIXCT_H_CT_MODE ISP_PARAM_AWB_V1_MIXCT_H_CT_MODE
#define isp_algo_param_awb_v1_mixct_mode_ISP_PARAM_AWB_V1_MIXCT_L_CT_MODE ISP_PARAM_AWB_V1_MIXCT_L_CT_MODE


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define isp_algo_param_header_t_init_default     {_isp_algo_param_header_value_t_MIN, _isp_algo_param_header_value_t_MIN}
#define isp_algo_param_index_t_init_default      {{0, 0}, {0, 0}, {0, 0}}
#define isp_algo_param_common_t_init_default     {"", isp_algo_param_index_t_init_default}
#define isp_algo_param_point_t_init_default      {0, 0}
#define isp_algo_param_blc_v1_t_init_default     {isp_algo_param_common_t_init_default}
#define isp_algo_param_blc_t_init_default        {0, {isp_algo_param_blc_v1_t_init_default}}
#define isp_algo_param_nlsc_v1_t_init_default    {isp_algo_param_common_t_init_default}
#define isp_algo_param_nlsc_t_init_default       {0, {isp_algo_param_nlsc_v1_t_init_default}}
#define isp_algo_param_mlsc_v1_t_init_default    {isp_algo_param_common_t_init_default}
#define isp_algo_param_mlsc_t_init_default       {0, {isp_algo_param_mlsc_v1_t_init_default}}
#define isp_algo_param_ccm_v1_t_init_default     {isp_algo_param_common_t_init_default}
#define isp_algo_param_ccm_t_init_default        {0, {isp_algo_param_ccm_v1_t_init_default}}
#define isp_algo_param_gamma_v1_t_init_default   {isp_algo_param_common_t_init_default}
#define isp_algo_param_gamma_t_init_default      {0, {isp_algo_param_gamma_v1_t_init_default}}
#define isp_algo_param_ygc_v1_t_init_default     {isp_algo_param_common_t_init_default}
#define isp_algo_param_ygc_t_init_default        {0, {isp_algo_param_ygc_v1_t_init_default}}
#define isp_algo_param_uvtune_v1_t_init_default  {isp_algo_param_common_t_init_default}
#define isp_algo_param_uvtune_t_init_default     {0, {isp_algo_param_uvtune_v1_t_init_default}}
#define isp_algo_param_spe_v1_t_init_default     {isp_algo_param_common_t_init_default}
#define isp_algo_param_spe_t_init_default        {0, {isp_algo_param_spe_v1_t_init_default}}
#define isp_algo_param_ygamma_v1_t_init_default  {isp_algo_param_common_t_init_default}
#define isp_algo_param_ygamma_t_init_default     {0, {isp_algo_param_ygamma_v1_t_init_default}}
#define isp_algo_param_texture_v1_t_init_default {isp_algo_param_common_t_init_default, 0, {isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default, isp_algo_param_common_t_init_default}}
#define isp_algo_param_texture_t_init_default    {0, {isp_algo_param_texture_v1_t_init_default}}
#define isp_algo_param_ae_v1_t_init_default      {isp_algo_param_common_t_init_default, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, _isp_algo_param_ae_v1_high_light_mode_MIN}
#define isp_algo_param_ae_t_init_default         {0, {isp_algo_param_ae_v1_t_init_default}}
#define isp_algo_param_awb_v1_t_init_default     {isp_algo_param_common_t_init_default, isp_algo_param_point_t_init_default, isp_algo_param_point_t_init_default, isp_algo_param_point_t_init_default, isp_algo_param_point_t_init_default, 0, 0, isp_algo_param_point_t_init_default, isp_algo_param_point_t_init_default, 0, 0, _isp_algo_param_awb_v1_mixct_mode_MIN}
#define isp_algo_param_awb_t_init_default        {0, {isp_algo_param_awb_v1_t_init_default}}
#define isp_algo_param_af_v1_t_init_default      {isp_algo_param_common_t_init_default, 0}
#define isp_algo_param_af_t_init_default         {0, {isp_algo_param_af_v1_t_init_default}}
#define isp_algo_param_flick_v1_t_init_default   {isp_algo_param_common_t_init_default, 0, 0, 0}
#define isp_algo_param_flick_t_init_default      {0, {isp_algo_param_flick_v1_t_init_default}}
#define isp_algo_param_wdr_v1_t_init_default     {isp_algo_param_common_t_init_default, 0, 0, 0, 0, 0, 0}
#define isp_algo_param_wdr_t_init_default        {0, {isp_algo_param_wdr_v1_t_init_default}}
#define isp_algo_param_daynight_v1_t_init_default {isp_algo_param_common_t_init_default}
#define isp_algo_param_daynight_t_init_default   {0, {isp_algo_param_daynight_v1_t_init_default}}
#define isp_algo_param_high_temp_v1_t_init_default {isp_algo_param_common_t_init_default, 0, 0}
#define isp_algo_param_high_temp_t_init_default  {0, {isp_algo_param_high_temp_v1_t_init_default}}
#define isp_algo_param_t_init_default            {isp_algo_param_header_t_init_default, isp_algo_param_blc_t_init_default, isp_algo_param_nlsc_t_init_default, isp_algo_param_mlsc_t_init_default, isp_algo_param_ccm_t_init_default, isp_algo_param_gamma_t_init_default, isp_algo_param_ygc_t_init_default, isp_algo_param_uvtune_t_init_default, isp_algo_param_spe_t_init_default, isp_algo_param_ygamma_t_init_default, isp_algo_param_texture_t_init_default, isp_algo_param_ae_t_init_default, isp_algo_param_awb_t_init_default, isp_algo_param_af_t_init_default, isp_algo_param_flick_t_init_default, isp_algo_param_wdr_t_init_default, isp_algo_param_daynight_t_init_default, isp_algo_param_high_temp_t_init_default}
#define isp_algo_param_header_t_init_zero        {_isp_algo_param_header_value_t_MIN, _isp_algo_param_header_value_t_MIN}
#define isp_algo_param_index_t_init_zero         {{0, 0}, {0, 0}, {0, 0}}
#define isp_algo_param_common_t_init_zero        {"", isp_algo_param_index_t_init_zero}
#define isp_algo_param_point_t_init_zero         {0, 0}
#define isp_algo_param_blc_v1_t_init_zero        {isp_algo_param_common_t_init_zero}
#define isp_algo_param_blc_t_init_zero           {0, {isp_algo_param_blc_v1_t_init_zero}}
#define isp_algo_param_nlsc_v1_t_init_zero       {isp_algo_param_common_t_init_zero}
#define isp_algo_param_nlsc_t_init_zero          {0, {isp_algo_param_nlsc_v1_t_init_zero}}
#define isp_algo_param_mlsc_v1_t_init_zero       {isp_algo_param_common_t_init_zero}
#define isp_algo_param_mlsc_t_init_zero          {0, {isp_algo_param_mlsc_v1_t_init_zero}}
#define isp_algo_param_ccm_v1_t_init_zero        {isp_algo_param_common_t_init_zero}
#define isp_algo_param_ccm_t_init_zero           {0, {isp_algo_param_ccm_v1_t_init_zero}}
#define isp_algo_param_gamma_v1_t_init_zero      {isp_algo_param_common_t_init_zero}
#define isp_algo_param_gamma_t_init_zero         {0, {isp_algo_param_gamma_v1_t_init_zero}}
#define isp_algo_param_ygc_v1_t_init_zero        {isp_algo_param_common_t_init_zero}
#define isp_algo_param_ygc_t_init_zero           {0, {isp_algo_param_ygc_v1_t_init_zero}}
#define isp_algo_param_uvtune_v1_t_init_zero     {isp_algo_param_common_t_init_zero}
#define isp_algo_param_uvtune_t_init_zero        {0, {isp_algo_param_uvtune_v1_t_init_zero}}
#define isp_algo_param_spe_v1_t_init_zero        {isp_algo_param_common_t_init_zero}
#define isp_algo_param_spe_t_init_zero           {0, {isp_algo_param_spe_v1_t_init_zero}}
#define isp_algo_param_ygamma_v1_t_init_zero     {isp_algo_param_common_t_init_zero}
#define isp_algo_param_ygamma_t_init_zero        {0, {isp_algo_param_ygamma_v1_t_init_zero}}
#define isp_algo_param_texture_v1_t_init_zero    {isp_algo_param_common_t_init_zero, 0, {isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero, isp_algo_param_common_t_init_zero}}
#define isp_algo_param_texture_t_init_zero       {0, {isp_algo_param_texture_v1_t_init_zero}}
#define isp_algo_param_ae_v1_t_init_zero         {isp_algo_param_common_t_init_zero, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, _isp_algo_param_ae_v1_high_light_mode_MIN}
#define isp_algo_param_ae_t_init_zero            {0, {isp_algo_param_ae_v1_t_init_zero}}
#define isp_algo_param_awb_v1_t_init_zero        {isp_algo_param_common_t_init_zero, isp_algo_param_point_t_init_zero, isp_algo_param_point_t_init_zero, isp_algo_param_point_t_init_zero, isp_algo_param_point_t_init_zero, 0, 0, isp_algo_param_point_t_init_zero, isp_algo_param_point_t_init_zero, 0, 0, _isp_algo_param_awb_v1_mixct_mode_MIN}
#define isp_algo_param_awb_t_init_zero           {0, {isp_algo_param_awb_v1_t_init_zero}}
#define isp_algo_param_af_v1_t_init_zero         {isp_algo_param_common_t_init_zero, 0}
#define isp_algo_param_af_t_init_zero            {0, {isp_algo_param_af_v1_t_init_zero}}
#define isp_algo_param_flick_v1_t_init_zero      {isp_algo_param_common_t_init_zero, 0, 0, 0}
#define isp_algo_param_flick_t_init_zero         {0, {isp_algo_param_flick_v1_t_init_zero}}
#define isp_algo_param_wdr_v1_t_init_zero        {isp_algo_param_common_t_init_zero, 0, 0, 0, 0, 0, 0}
#define isp_algo_param_wdr_t_init_zero           {0, {isp_algo_param_wdr_v1_t_init_zero}}
#define isp_algo_param_daynight_v1_t_init_zero   {isp_algo_param_common_t_init_zero}
#define isp_algo_param_daynight_t_init_zero      {0, {isp_algo_param_daynight_v1_t_init_zero}}
#define isp_algo_param_high_temp_v1_t_init_zero  {isp_algo_param_common_t_init_zero, 0, 0}
#define isp_algo_param_high_temp_t_init_zero     {0, {isp_algo_param_high_temp_v1_t_init_zero}}
#define isp_algo_param_t_init_zero               {isp_algo_param_header_t_init_zero, isp_algo_param_blc_t_init_zero, isp_algo_param_nlsc_t_init_zero, isp_algo_param_mlsc_t_init_zero, isp_algo_param_ccm_t_init_zero, isp_algo_param_gamma_t_init_zero, isp_algo_param_ygc_t_init_zero, isp_algo_param_uvtune_t_init_zero, isp_algo_param_spe_t_init_zero, isp_algo_param_ygamma_t_init_zero, isp_algo_param_texture_t_init_zero, isp_algo_param_ae_t_init_zero, isp_algo_param_awb_t_init_zero, isp_algo_param_af_t_init_zero, isp_algo_param_flick_t_init_zero, isp_algo_param_wdr_t_init_zero, isp_algo_param_daynight_t_init_zero, isp_algo_param_high_temp_t_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define isp_algo_param_header_t_magic_tag        1
#define isp_algo_param_header_t_version_tag      2
#define isp_algo_param_index_t_indexes_tag       1
#define isp_algo_param_index_t_indexes0_tag      2
#define isp_algo_param_index_t_indexes1_tag      3
#define isp_algo_param_point_t_x_tag             1
#define isp_algo_param_point_t_y_tag             2
#define isp_algo_param_common_t_name_tag         1
#define isp_algo_param_common_t_index_tag        2
#define isp_algo_param_ae_v1_t_common_tag        1
#define isp_algo_param_ae_v1_t_y_mean_tag        2
#define isp_algo_param_ae_v1_t_gain_tag          3
#define isp_algo_param_ae_v1_t_exposure_tag      4
#define isp_algo_param_ae_v1_t_saturated_ratio_tag 5
#define isp_algo_param_ae_v1_t_ae_ctrl_force_tag 6
#define isp_algo_param_ae_v1_t_dark_sort_index_tag 7
#define isp_algo_param_ae_v1_t_bright_sort_index_tag 8
#define isp_algo_param_ae_v1_t_max_et_index_tag  9
#define isp_algo_param_ae_v1_t_etgain_ratio_tag  10
#define isp_algo_param_ae_v1_t_hdr_mean_tag      11
#define isp_algo_param_ae_v1_t_hdr_over_ratio_tag 12
#define isp_algo_param_ae_v1_t_hdr_stable_info_tag 13
#define isp_algo_param_ae_v1_t_analog_gain_tag   14
#define isp_algo_param_ae_v1_t_digital_gain_tag  15
#define isp_algo_param_ae_v1_t_isp_hdr_gain_tag  16
#define isp_algo_param_ae_v1_t_isp_gain_tag      17
#define isp_algo_param_ae_v1_t_ratio_range_index_tag 18
#define isp_algo_param_ae_v1_t_roi_y_mean_tag    19
#define isp_algo_param_ae_v1_t_non_roi_y_mean_tag 20
#define isp_algo_param_ae_v1_t_frame_y_mean_tag  21
#define isp_algo_param_ae_v1_t_same_block_num_tag 22
#define isp_algo_param_ae_v1_t_target_delta_tag  23
#define isp_algo_param_ae_v1_t_high_light_mode_tag 24
#define isp_algo_param_af_v1_t_common_tag        1
#define isp_algo_param_af_v1_t_af_ctrl_force_tag 2
#define isp_algo_param_awb_v1_t_common_tag       1
#define isp_algo_param_awb_v1_t_gray_gain_tag    2
#define isp_algo_param_awb_v1_t_green_gain_tag   3
#define isp_algo_param_awb_v1_t_rough_gain_tag   4
#define isp_algo_param_awb_v1_t_result_gain_tag  5
#define isp_algo_param_awb_v1_t_color_temperature_tag 6
#define isp_algo_param_awb_v1_t_awb_ctrl_force_tag 7
#define isp_algo_param_awb_v1_t_final_gain_tag   8
#define isp_algo_param_awb_v1_t_gain_adj_tag     9
#define isp_algo_param_awb_v1_t_gray_num_tag     10
#define isp_algo_param_awb_v1_t_green_num_tag    11
#define isp_algo_param_awb_v1_t_mixct_mode_tag   12
#define isp_algo_param_blc_v1_t_common_tag       1
#define isp_algo_param_ccm_v1_t_common_tag       1
#define isp_algo_param_daynight_v1_t_common_tag  1
#define isp_algo_param_flick_v1_t_common_tag     1
#define isp_algo_param_flick_v1_t_insert_dummy_line_tag 2
#define isp_algo_param_flick_v1_t_cur_freq_tag   3
#define isp_algo_param_flick_v1_t_flick_ctrl_force_tag 4
#define isp_algo_param_gamma_v1_t_common_tag     1
#define isp_algo_param_high_temp_v1_t_common_tag 1
#define isp_algo_param_high_temp_v1_t_high_temp_en_tag 2
#define isp_algo_param_high_temp_v1_t_sensor_temperature_tag 3
#define isp_algo_param_mlsc_v1_t_common_tag      1
#define isp_algo_param_nlsc_v1_t_common_tag      1
#define isp_algo_param_spe_v1_t_common_tag       1
#define isp_algo_param_texture_v1_t_common_tag   1
#define isp_algo_param_texture_v1_t_nests_tag    2
#define isp_algo_param_uvtune_v1_t_common_tag    1
#define isp_algo_param_wdr_v1_t_common_tag       1
#define isp_algo_param_wdr_v1_t_day_night_tag    2
#define isp_algo_param_wdr_v1_t_low_bound_tag    3
#define isp_algo_param_wdr_v1_t_wdr_level_tag    4
#define isp_algo_param_wdr_v1_t_wdr_ctrl_force_tag 5
#define isp_algo_param_wdr_v1_t_hist_contrast_origin_tag 6
#define isp_algo_param_wdr_v1_t_hist_contrast_tag 7
#define isp_algo_param_ygamma_v1_t_common_tag    1
#define isp_algo_param_ygc_v1_t_common_tag       1
#define isp_algo_param_ae_t_v1_tag               1
#define isp_algo_param_af_t_v1_tag               1
#define isp_algo_param_awb_t_v1_tag              1
#define isp_algo_param_blc_t_v1_tag              1
#define isp_algo_param_ccm_t_v1_tag              1
#define isp_algo_param_daynight_t_v1_tag         1
#define isp_algo_param_flick_t_v1_tag            1
#define isp_algo_param_gamma_t_v1_tag            1
#define isp_algo_param_high_temp_t_v1_tag        1
#define isp_algo_param_mlsc_t_v1_tag             1
#define isp_algo_param_nlsc_t_v1_tag             1
#define isp_algo_param_spe_t_v1_tag              1
#define isp_algo_param_texture_t_v1_tag          1
#define isp_algo_param_uvtune_t_v1_tag           1
#define isp_algo_param_wdr_t_v1_tag              1
#define isp_algo_param_ygamma_t_v1_tag           1
#define isp_algo_param_ygc_t_v1_tag              1
#define isp_algo_param_t_header_tag              1
#define isp_algo_param_t_blc_tag                 2
#define isp_algo_param_t_nlsc_tag                3
#define isp_algo_param_t_mlsc_tag                4
#define isp_algo_param_t_ccm_tag                 5
#define isp_algo_param_t_gamma_tag               6
#define isp_algo_param_t_ygc_tag                 7
#define isp_algo_param_t_uvtune_tag              8
#define isp_algo_param_t_spe_tag                 9
#define isp_algo_param_t_ygamma_tag              10
#define isp_algo_param_t_texture_tag             11
#define isp_algo_param_t_ae_tag                  32
#define isp_algo_param_t_awb_tag                 33
#define isp_algo_param_t_af_tag                  34
#define isp_algo_param_t_flick_tag               35
#define isp_algo_param_t_wdr_tag                 36
#define isp_algo_param_t_daynight_tag            37
#define isp_algo_param_t_high_temp_tag           38

/* Struct field encoding specification for nanopb */
#define isp_algo_param_header_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    magic,             1) \
X(a, STATIC,   SINGULAR, UENUM,    version,           2)
#define isp_algo_param_header_t_CALLBACK NULL
#define isp_algo_param_header_t_DEFAULT NULL

#define isp_algo_param_index_t_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   indexes,           1) \
X(a, STATIC,   FIXARRAY, UINT32,   indexes0,          2) \
X(a, STATIC,   FIXARRAY, UINT32,   indexes1,          3)
#define isp_algo_param_index_t_CALLBACK NULL
#define isp_algo_param_index_t_DEFAULT NULL

#define isp_algo_param_common_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, MESSAGE,  index,             2)
#define isp_algo_param_common_t_CALLBACK NULL
#define isp_algo_param_common_t_DEFAULT NULL
#define isp_algo_param_common_t_index_MSGTYPE isp_algo_param_index_t

#define isp_algo_param_point_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define isp_algo_param_point_t_CALLBACK NULL
#define isp_algo_param_point_t_DEFAULT NULL

#define isp_algo_param_blc_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_blc_v1_t_CALLBACK NULL
#define isp_algo_param_blc_v1_t_DEFAULT NULL
#define isp_algo_param_blc_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_blc_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_blc_t_CALLBACK NULL
#define isp_algo_param_blc_t_DEFAULT NULL
#define isp_algo_param_blc_t_entry_v1_MSGTYPE isp_algo_param_blc_v1_t

#define isp_algo_param_nlsc_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_nlsc_v1_t_CALLBACK NULL
#define isp_algo_param_nlsc_v1_t_DEFAULT NULL
#define isp_algo_param_nlsc_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_nlsc_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_nlsc_t_CALLBACK NULL
#define isp_algo_param_nlsc_t_DEFAULT NULL
#define isp_algo_param_nlsc_t_entry_v1_MSGTYPE isp_algo_param_nlsc_v1_t

#define isp_algo_param_mlsc_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_mlsc_v1_t_CALLBACK NULL
#define isp_algo_param_mlsc_v1_t_DEFAULT NULL
#define isp_algo_param_mlsc_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_mlsc_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_mlsc_t_CALLBACK NULL
#define isp_algo_param_mlsc_t_DEFAULT NULL
#define isp_algo_param_mlsc_t_entry_v1_MSGTYPE isp_algo_param_mlsc_v1_t

#define isp_algo_param_ccm_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_ccm_v1_t_CALLBACK NULL
#define isp_algo_param_ccm_v1_t_DEFAULT NULL
#define isp_algo_param_ccm_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_ccm_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_ccm_t_CALLBACK NULL
#define isp_algo_param_ccm_t_DEFAULT NULL
#define isp_algo_param_ccm_t_entry_v1_MSGTYPE isp_algo_param_ccm_v1_t

#define isp_algo_param_gamma_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_gamma_v1_t_CALLBACK NULL
#define isp_algo_param_gamma_v1_t_DEFAULT NULL
#define isp_algo_param_gamma_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_gamma_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_gamma_t_CALLBACK NULL
#define isp_algo_param_gamma_t_DEFAULT NULL
#define isp_algo_param_gamma_t_entry_v1_MSGTYPE isp_algo_param_gamma_v1_t

#define isp_algo_param_ygc_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_ygc_v1_t_CALLBACK NULL
#define isp_algo_param_ygc_v1_t_DEFAULT NULL
#define isp_algo_param_ygc_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_ygc_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_ygc_t_CALLBACK NULL
#define isp_algo_param_ygc_t_DEFAULT NULL
#define isp_algo_param_ygc_t_entry_v1_MSGTYPE isp_algo_param_ygc_v1_t

#define isp_algo_param_uvtune_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_uvtune_v1_t_CALLBACK NULL
#define isp_algo_param_uvtune_v1_t_DEFAULT NULL
#define isp_algo_param_uvtune_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_uvtune_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_uvtune_t_CALLBACK NULL
#define isp_algo_param_uvtune_t_DEFAULT NULL
#define isp_algo_param_uvtune_t_entry_v1_MSGTYPE isp_algo_param_uvtune_v1_t

#define isp_algo_param_spe_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_spe_v1_t_CALLBACK NULL
#define isp_algo_param_spe_v1_t_DEFAULT NULL
#define isp_algo_param_spe_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_spe_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_spe_t_CALLBACK NULL
#define isp_algo_param_spe_t_DEFAULT NULL
#define isp_algo_param_spe_t_entry_v1_MSGTYPE isp_algo_param_spe_v1_t

#define isp_algo_param_ygamma_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_ygamma_v1_t_CALLBACK NULL
#define isp_algo_param_ygamma_v1_t_DEFAULT NULL
#define isp_algo_param_ygamma_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_ygamma_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_ygamma_t_CALLBACK NULL
#define isp_algo_param_ygamma_t_DEFAULT NULL
#define isp_algo_param_ygamma_t_entry_v1_MSGTYPE isp_algo_param_ygamma_v1_t

#define isp_algo_param_texture_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  nests,             2)
#define isp_algo_param_texture_v1_t_CALLBACK NULL
#define isp_algo_param_texture_v1_t_DEFAULT NULL
#define isp_algo_param_texture_v1_t_common_MSGTYPE isp_algo_param_common_t
#define isp_algo_param_texture_v1_t_nests_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_texture_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_texture_t_CALLBACK NULL
#define isp_algo_param_texture_t_DEFAULT NULL
#define isp_algo_param_texture_t_entry_v1_MSGTYPE isp_algo_param_texture_v1_t

#define isp_algo_param_ae_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, UINT32,   y_mean,            2) \
X(a, STATIC,   FIXARRAY, FLOAT,    gain,              3) \
X(a, STATIC,   FIXARRAY, FLOAT,    exposure,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    saturated_ratio,   5) \
X(a, STATIC,   SINGULAR, BOOL,     ae_ctrl_force,     6) \
X(a, STATIC,   SINGULAR, UINT32,   dark_sort_index,   7) \
X(a, STATIC,   SINGULAR, UINT32,   bright_sort_index,   8) \
X(a, STATIC,   SINGULAR, UINT32,   max_et_index,      9) \
X(a, STATIC,   FIXARRAY, FLOAT,    etgain_ratio,     10) \
X(a, STATIC,   FIXARRAY, UINT32,   hdr_mean,         11) \
X(a, STATIC,   FIXARRAY, FLOAT,    hdr_over_ratio,   12) \
X(a, STATIC,   FIXARRAY, UINT32,   hdr_stable_info,  13) \
X(a, STATIC,   FIXARRAY, FLOAT,    analog_gain,      14) \
X(a, STATIC,   FIXARRAY, FLOAT,    digital_gain,     15) \
X(a, STATIC,   FIXARRAY, FLOAT,    isp_hdr_gain,     16) \
X(a, STATIC,   SINGULAR, FLOAT,    isp_gain,         17) \
X(a, STATIC,   SINGULAR, UINT32,   ratio_range_index,  18) \
X(a, STATIC,   SINGULAR, UINT32,   roi_y_mean,       19) \
X(a, STATIC,   SINGULAR, UINT32,   non_roi_y_mean,   20) \
X(a, STATIC,   SINGULAR, UINT32,   frame_y_mean,     21) \
X(a, STATIC,   SINGULAR, UINT32,   same_block_num,   22) \
X(a, STATIC,   SINGULAR, INT32,    target_delta,     23) \
X(a, STATIC,   SINGULAR, UENUM,    high_light_mode,  24)
#define isp_algo_param_ae_v1_t_CALLBACK NULL
#define isp_algo_param_ae_v1_t_DEFAULT NULL
#define isp_algo_param_ae_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_ae_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_ae_t_CALLBACK NULL
#define isp_algo_param_ae_t_DEFAULT NULL
#define isp_algo_param_ae_t_entry_v1_MSGTYPE isp_algo_param_ae_v1_t

#define isp_algo_param_awb_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, MESSAGE,  gray_gain,         2) \
X(a, STATIC,   SINGULAR, MESSAGE,  green_gain,        3) \
X(a, STATIC,   SINGULAR, MESSAGE,  rough_gain,        4) \
X(a, STATIC,   SINGULAR, MESSAGE,  result_gain,       5) \
X(a, STATIC,   SINGULAR, UINT32,   color_temperature,   6) \
X(a, STATIC,   SINGULAR, BOOL,     awb_ctrl_force,    7) \
X(a, STATIC,   SINGULAR, MESSAGE,  final_gain,        8) \
X(a, STATIC,   SINGULAR, MESSAGE,  gain_adj,          9) \
X(a, STATIC,   SINGULAR, UINT32,   gray_num,         10) \
X(a, STATIC,   SINGULAR, UINT32,   green_num,        11) \
X(a, STATIC,   SINGULAR, UENUM,    mixct_mode,       12)
#define isp_algo_param_awb_v1_t_CALLBACK NULL
#define isp_algo_param_awb_v1_t_DEFAULT NULL
#define isp_algo_param_awb_v1_t_common_MSGTYPE isp_algo_param_common_t
#define isp_algo_param_awb_v1_t_gray_gain_MSGTYPE isp_algo_param_point_t
#define isp_algo_param_awb_v1_t_green_gain_MSGTYPE isp_algo_param_point_t
#define isp_algo_param_awb_v1_t_rough_gain_MSGTYPE isp_algo_param_point_t
#define isp_algo_param_awb_v1_t_result_gain_MSGTYPE isp_algo_param_point_t
#define isp_algo_param_awb_v1_t_final_gain_MSGTYPE isp_algo_param_point_t
#define isp_algo_param_awb_v1_t_gain_adj_MSGTYPE isp_algo_param_point_t

#define isp_algo_param_awb_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_awb_t_CALLBACK NULL
#define isp_algo_param_awb_t_DEFAULT NULL
#define isp_algo_param_awb_t_entry_v1_MSGTYPE isp_algo_param_awb_v1_t

#define isp_algo_param_af_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, BOOL,     af_ctrl_force,     2)
#define isp_algo_param_af_v1_t_CALLBACK NULL
#define isp_algo_param_af_v1_t_DEFAULT NULL
#define isp_algo_param_af_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_af_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_af_t_CALLBACK NULL
#define isp_algo_param_af_t_DEFAULT NULL
#define isp_algo_param_af_t_entry_v1_MSGTYPE isp_algo_param_af_v1_t

#define isp_algo_param_flick_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, UINT32,   insert_dummy_line,   2) \
X(a, STATIC,   SINGULAR, UINT32,   cur_freq,          3) \
X(a, STATIC,   SINGULAR, BOOL,     flick_ctrl_force,   4)
#define isp_algo_param_flick_v1_t_CALLBACK NULL
#define isp_algo_param_flick_v1_t_DEFAULT NULL
#define isp_algo_param_flick_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_flick_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_flick_t_CALLBACK NULL
#define isp_algo_param_flick_t_DEFAULT NULL
#define isp_algo_param_flick_t_entry_v1_MSGTYPE isp_algo_param_flick_v1_t

#define isp_algo_param_wdr_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, UINT32,   day_night,         2) \
X(a, STATIC,   SINGULAR, UINT32,   low_bound,         3) \
X(a, STATIC,   SINGULAR, UINT32,   wdr_level,         4) \
X(a, STATIC,   SINGULAR, BOOL,     wdr_ctrl_force,    5) \
X(a, STATIC,   SINGULAR, UINT32,   hist_contrast_origin,   6) \
X(a, STATIC,   SINGULAR, UINT32,   hist_contrast,     7)
#define isp_algo_param_wdr_v1_t_CALLBACK NULL
#define isp_algo_param_wdr_v1_t_DEFAULT NULL
#define isp_algo_param_wdr_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_wdr_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_wdr_t_CALLBACK NULL
#define isp_algo_param_wdr_t_DEFAULT NULL
#define isp_algo_param_wdr_t_entry_v1_MSGTYPE isp_algo_param_wdr_v1_t

#define isp_algo_param_daynight_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1)
#define isp_algo_param_daynight_v1_t_CALLBACK NULL
#define isp_algo_param_daynight_v1_t_DEFAULT NULL
#define isp_algo_param_daynight_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_daynight_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_daynight_t_CALLBACK NULL
#define isp_algo_param_daynight_t_DEFAULT NULL
#define isp_algo_param_daynight_t_entry_v1_MSGTYPE isp_algo_param_daynight_v1_t

#define isp_algo_param_high_temp_v1_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  common,            1) \
X(a, STATIC,   SINGULAR, BOOL,     high_temp_en,      2) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_temperature,   3)
#define isp_algo_param_high_temp_v1_t_CALLBACK NULL
#define isp_algo_param_high_temp_v1_t_DEFAULT NULL
#define isp_algo_param_high_temp_v1_t_common_MSGTYPE isp_algo_param_common_t

#define isp_algo_param_high_temp_t_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (entry,v1,entry.v1),   1)
#define isp_algo_param_high_temp_t_CALLBACK NULL
#define isp_algo_param_high_temp_t_DEFAULT NULL
#define isp_algo_param_high_temp_t_entry_v1_MSGTYPE isp_algo_param_high_temp_v1_t

#define isp_algo_param_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, MESSAGE,  blc,               2) \
X(a, STATIC,   SINGULAR, MESSAGE,  nlsc,              3) \
X(a, STATIC,   SINGULAR, MESSAGE,  mlsc,              4) \
X(a, STATIC,   SINGULAR, MESSAGE,  ccm,               5) \
X(a, STATIC,   SINGULAR, MESSAGE,  gamma,             6) \
X(a, STATIC,   SINGULAR, MESSAGE,  ygc,               7) \
X(a, STATIC,   SINGULAR, MESSAGE,  uvtune,            8) \
X(a, STATIC,   SINGULAR, MESSAGE,  spe,               9) \
X(a, STATIC,   SINGULAR, MESSAGE,  ygamma,           10) \
X(a, STATIC,   SINGULAR, MESSAGE,  texture,          11) \
X(a, STATIC,   SINGULAR, MESSAGE,  ae,               32) \
X(a, STATIC,   SINGULAR, MESSAGE,  awb,              33) \
X(a, STATIC,   SINGULAR, MESSAGE,  af,               34) \
X(a, STATIC,   SINGULAR, MESSAGE,  flick,            35) \
X(a, STATIC,   SINGULAR, MESSAGE,  wdr,              36) \
X(a, STATIC,   SINGULAR, MESSAGE,  daynight,         37) \
X(a, STATIC,   SINGULAR, MESSAGE,  high_temp,        38)
#define isp_algo_param_t_CALLBACK NULL
#define isp_algo_param_t_DEFAULT NULL
#define isp_algo_param_t_header_MSGTYPE isp_algo_param_header_t
#define isp_algo_param_t_blc_MSGTYPE isp_algo_param_blc_t
#define isp_algo_param_t_nlsc_MSGTYPE isp_algo_param_nlsc_t
#define isp_algo_param_t_mlsc_MSGTYPE isp_algo_param_mlsc_t
#define isp_algo_param_t_ccm_MSGTYPE isp_algo_param_ccm_t
#define isp_algo_param_t_gamma_MSGTYPE isp_algo_param_gamma_t
#define isp_algo_param_t_ygc_MSGTYPE isp_algo_param_ygc_t
#define isp_algo_param_t_uvtune_MSGTYPE isp_algo_param_uvtune_t
#define isp_algo_param_t_spe_MSGTYPE isp_algo_param_spe_t
#define isp_algo_param_t_ygamma_MSGTYPE isp_algo_param_ygamma_t
#define isp_algo_param_t_texture_MSGTYPE isp_algo_param_texture_t
#define isp_algo_param_t_ae_MSGTYPE isp_algo_param_ae_t
#define isp_algo_param_t_awb_MSGTYPE isp_algo_param_awb_t
#define isp_algo_param_t_af_MSGTYPE isp_algo_param_af_t
#define isp_algo_param_t_flick_MSGTYPE isp_algo_param_flick_t
#define isp_algo_param_t_wdr_MSGTYPE isp_algo_param_wdr_t
#define isp_algo_param_t_daynight_MSGTYPE isp_algo_param_daynight_t
#define isp_algo_param_t_high_temp_MSGTYPE isp_algo_param_high_temp_t

extern const pb_msgdesc_t isp_algo_param_header_t_msg;
extern const pb_msgdesc_t isp_algo_param_index_t_msg;
extern const pb_msgdesc_t isp_algo_param_common_t_msg;
extern const pb_msgdesc_t isp_algo_param_point_t_msg;
extern const pb_msgdesc_t isp_algo_param_blc_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_blc_t_msg;
extern const pb_msgdesc_t isp_algo_param_nlsc_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_nlsc_t_msg;
extern const pb_msgdesc_t isp_algo_param_mlsc_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_mlsc_t_msg;
extern const pb_msgdesc_t isp_algo_param_ccm_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_ccm_t_msg;
extern const pb_msgdesc_t isp_algo_param_gamma_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_gamma_t_msg;
extern const pb_msgdesc_t isp_algo_param_ygc_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_ygc_t_msg;
extern const pb_msgdesc_t isp_algo_param_uvtune_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_uvtune_t_msg;
extern const pb_msgdesc_t isp_algo_param_spe_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_spe_t_msg;
extern const pb_msgdesc_t isp_algo_param_ygamma_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_ygamma_t_msg;
extern const pb_msgdesc_t isp_algo_param_texture_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_texture_t_msg;
extern const pb_msgdesc_t isp_algo_param_ae_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_ae_t_msg;
extern const pb_msgdesc_t isp_algo_param_awb_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_awb_t_msg;
extern const pb_msgdesc_t isp_algo_param_af_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_af_t_msg;
extern const pb_msgdesc_t isp_algo_param_flick_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_flick_t_msg;
extern const pb_msgdesc_t isp_algo_param_wdr_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_wdr_t_msg;
extern const pb_msgdesc_t isp_algo_param_daynight_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_daynight_t_msg;
extern const pb_msgdesc_t isp_algo_param_high_temp_v1_t_msg;
extern const pb_msgdesc_t isp_algo_param_high_temp_t_msg;
extern const pb_msgdesc_t isp_algo_param_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define isp_algo_param_header_t_fields &isp_algo_param_header_t_msg
#define isp_algo_param_index_t_fields &isp_algo_param_index_t_msg
#define isp_algo_param_common_t_fields &isp_algo_param_common_t_msg
#define isp_algo_param_point_t_fields &isp_algo_param_point_t_msg
#define isp_algo_param_blc_v1_t_fields &isp_algo_param_blc_v1_t_msg
#define isp_algo_param_blc_t_fields &isp_algo_param_blc_t_msg
#define isp_algo_param_nlsc_v1_t_fields &isp_algo_param_nlsc_v1_t_msg
#define isp_algo_param_nlsc_t_fields &isp_algo_param_nlsc_t_msg
#define isp_algo_param_mlsc_v1_t_fields &isp_algo_param_mlsc_v1_t_msg
#define isp_algo_param_mlsc_t_fields &isp_algo_param_mlsc_t_msg
#define isp_algo_param_ccm_v1_t_fields &isp_algo_param_ccm_v1_t_msg
#define isp_algo_param_ccm_t_fields &isp_algo_param_ccm_t_msg
#define isp_algo_param_gamma_v1_t_fields &isp_algo_param_gamma_v1_t_msg
#define isp_algo_param_gamma_t_fields &isp_algo_param_gamma_t_msg
#define isp_algo_param_ygc_v1_t_fields &isp_algo_param_ygc_v1_t_msg
#define isp_algo_param_ygc_t_fields &isp_algo_param_ygc_t_msg
#define isp_algo_param_uvtune_v1_t_fields &isp_algo_param_uvtune_v1_t_msg
#define isp_algo_param_uvtune_t_fields &isp_algo_param_uvtune_t_msg
#define isp_algo_param_spe_v1_t_fields &isp_algo_param_spe_v1_t_msg
#define isp_algo_param_spe_t_fields &isp_algo_param_spe_t_msg
#define isp_algo_param_ygamma_v1_t_fields &isp_algo_param_ygamma_v1_t_msg
#define isp_algo_param_ygamma_t_fields &isp_algo_param_ygamma_t_msg
#define isp_algo_param_texture_v1_t_fields &isp_algo_param_texture_v1_t_msg
#define isp_algo_param_texture_t_fields &isp_algo_param_texture_t_msg
#define isp_algo_param_ae_v1_t_fields &isp_algo_param_ae_v1_t_msg
#define isp_algo_param_ae_t_fields &isp_algo_param_ae_t_msg
#define isp_algo_param_awb_v1_t_fields &isp_algo_param_awb_v1_t_msg
#define isp_algo_param_awb_t_fields &isp_algo_param_awb_t_msg
#define isp_algo_param_af_v1_t_fields &isp_algo_param_af_v1_t_msg
#define isp_algo_param_af_t_fields &isp_algo_param_af_t_msg
#define isp_algo_param_flick_v1_t_fields &isp_algo_param_flick_v1_t_msg
#define isp_algo_param_flick_t_fields &isp_algo_param_flick_t_msg
#define isp_algo_param_wdr_v1_t_fields &isp_algo_param_wdr_v1_t_msg
#define isp_algo_param_wdr_t_fields &isp_algo_param_wdr_t_msg
#define isp_algo_param_daynight_v1_t_fields &isp_algo_param_daynight_v1_t_msg
#define isp_algo_param_daynight_t_fields &isp_algo_param_daynight_t_msg
#define isp_algo_param_high_temp_v1_t_fields &isp_algo_param_high_temp_v1_t_msg
#define isp_algo_param_high_temp_t_fields &isp_algo_param_high_temp_t_msg
#define isp_algo_param_t_fields &isp_algo_param_t_msg

/* Maximum encoded size of messages (where known) */
#define isp_algo_param_ae_t_size                 310
#define isp_algo_param_ae_v1_t_size              307
#define isp_algo_param_af_t_size                 59
#define isp_algo_param_af_v1_t_size              57
#define isp_algo_param_awb_t_size                140
#define isp_algo_param_awb_v1_t_size             137
#define isp_algo_param_blc_t_size                57
#define isp_algo_param_blc_v1_t_size             55
#define isp_algo_param_ccm_t_size                57
#define isp_algo_param_ccm_v1_t_size             55
#define isp_algo_param_common_t_size             53
#define isp_algo_param_daynight_t_size           57
#define isp_algo_param_daynight_v1_t_size        55
#define isp_algo_param_flick_t_size              69
#define isp_algo_param_flick_v1_t_size           67
#define isp_algo_param_gamma_t_size              57
#define isp_algo_param_gamma_v1_t_size           55
#define isp_algo_param_header_t_size             12
#define isp_algo_param_high_temp_t_size          65
#define isp_algo_param_high_temp_v1_t_size       63
#define isp_algo_param_index_t_size              18
#define isp_algo_param_mlsc_t_size               57
#define isp_algo_param_mlsc_v1_t_size            55
#define isp_algo_param_nlsc_t_size               57
#define isp_algo_param_nlsc_v1_t_size            55
#define isp_algo_param_point_t_size              8
#define isp_algo_param_spe_t_size                57
#define isp_algo_param_spe_v1_t_size             55
#define isp_algo_param_t_size                    2289
#define isp_algo_param_texture_t_size            938
#define isp_algo_param_texture_v1_t_size         935
#define isp_algo_param_uvtune_t_size             57
#define isp_algo_param_uvtune_v1_t_size          55
#define isp_algo_param_wdr_t_size                80
#define isp_algo_param_wdr_v1_t_size             78
#define isp_algo_param_ygamma_t_size             57
#define isp_algo_param_ygamma_v1_t_size          55
#define isp_algo_param_ygc_t_size                57
#define isp_algo_param_ygc_v1_t_size             55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
